Modification to make owner of region inside of it if the box contains it
LaNoC-UFC/rsbr pull request #100
Opened 2016-12-01 13:34 UTC by rafaelgmota

If box of region contains the owner he will be included at region, with this we decrease the number of generated regions

2016-12-01 13:42 UTC, rmilfont commented on src/rbr/RBR.java
> +        Range box = r.box();
I think that you can remove this line and put in the return statement

2016-12-01 13:49 UTC, rmilfont commented on src/rbr/RBR.java
> +            Set<Vertex> destinations = new HashSet<>();
You don´t have to do this new.

2016-12-01 13:50 UTC, rmilfont commented on src/rbr/RBR.java
> +            newRegions.addAll(adjustedRegionsFrom(adjustRegionWithOwner(currentRegion, sw)));
I think that you can rearrange this in order to make more clear (remove the 'if' from adjustRegionWithOwner)

2016-12-01 13:50 UTC, rmilfont requested changes
Some little changes

2016-12-01 17:38 UTC, jmferreiratech requested changes

2016-12-01 17:38 UTC, jmarcelof commented on src/rbr/RBR.java
> +    private boolean isOwnerInside(Region r, Vertex owner) {
Check if the region's outsiders contains the 'owner' instead.

2016-12-01 17:38 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +    public void adjustedRegionsOwnerInsideRegion() throws Exception {
I'd add a test showing that the adjustedRegion is the same original region when the owner is not inside the box.

2016-12-01 17:38 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +        Assert.assertTrue(owner.isIn(box));
I'd assert only that the adjustedRegion's outsiders is empty.

2016-12-01 17:38 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +    public void adjustedRegionsOwnerInsideRegion() throws Exception {
Your test name should be 'sentence like', stating something that is true. I'd name this one 'adjustedRegionContainsOwner' or something like that.

2016-12-01 17:38 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +    Set<Character> ip = new HashSet<>();
Couldn't these be private?

2016-12-02 14:32 UTC, rafaelgmota commented
Done

2016-12-02 18:16 UTC, rmilfont approved these changes

2016-12-05 12:33 UTC, jmferreiratech requested changes
Please add an ignored test to the case which even with others outsiders the owner should be included to decrease the number of regions.

2016-12-05 12:33 UTC, jmarcelof commented on src/rbr/RBR.java
> +            destinations.add(owner);
Make the 'if' surround only the line 135.

2016-12-05 12:33 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +    public void adjustedRegionIsTheSameWhenOwnerAreNotInsideTheBox() throws Exception {
Rename to 'adjustedRegionIsTheSameWhenOwnerIsNotInsideBox'.

2016-12-05 12:33 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +    public void adjustedRegionContainsOwner() throws Exception {
Rename to 'adjustedRegionIncludesOwnerWhenItIsTheOnlyOutsider'.

2016-12-05 12:33 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +        Assert.assertTrue(adjustedRegion.outsiders().size() == 0);
Use assertEquals.

2016-12-05 12:33 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +    public void adjustedRegionNotContainsOwner() throws Exception {
Rename to 'adjustedRegionDoNotIncludeOwnerWhenThereAreOthersOutsiders'.

2016-12-05 17:41 UTC, rafaelgmota commented
(y)

2016-12-12 14:45 UTC, jmferreiratech requested changes

2016-12-12 14:45 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +    public void adjustedRegionNotContainsOwner() throws Exception {
Make this test name more 'sentence like'... which case are you trying to show?

2016-12-12 14:45 UTC, jmarcelof commented on tests/rbr/adjustRegionWithOwnerTest.java
> +    Set<Character> ip = new HashSet<>();
No?

2016-12-26 20:05 UTC, jmarcelof commented
Already merged.

2016-12-26 20:05 UTC, closed without merging