Implement Deterministic Faulty Graph Builder
LaNoC-UFC/rsbr pull request #113
Opened 2017-01-11 15:43 UTC by danieldgt

Now, is possible to generate graph with all combinations of possible fault links

Commit:Add

2017-01-11 18:36 UTC, jmferreiratech requested changes

2017-01-11 18:36 UTC, jmarcelof commented on src/util/Combinatorics.java
> +    public static List<Set> allCombinationsOf(Set objects, int maxSize) {
You're not using this method, therefore you can remove it.

2017-01-11 18:36 UTC, jmarcelof commented on src/util/Combinatorics.java
> +    public static List<Set> allCombinationsOf(Set objects) {
Could it be made a [generic method](https://docs.oracle.com/javase/tutorial/extra/generics/methods.html)?

2017-01-11 18:36 UTC, jmarcelof commented on src/util/DeterministicFaultyGraphBuilder.java
> +        Integer result = (int) CombinatoricsUtils.binomialCoefficient(n, k);
That dependency should be hidden at 'util.Combinatorics'. Better than that we could implement it.

2017-01-11 18:36 UTC, jmarcelof commented on src/util/DeterministicFaultyGraphBuilder.java
> +}
Always place a newline before EOF.

2017-01-11 18:36 UTC, jmarcelof commented on src/util/DeterministicFaultyGraphBuilder.java
> +    static public Graph generateGraph(int rows, int columns, int index) {
Please break this method. It's way too big.

2017-01-11 18:36 UTC, jmarcelof commented on src/util/DeterministicFaultyGraphBuilder.java
> +
Please check how we use vertical indent on our code base.

2017-01-12 11:04 UTC, jmarcelof commented on src/util/Combinatorics.java
> +    public static List<Set> allCombinationsOf(Set objects) {
And please, make the constructor of Combinatorics private.

2017-01-12 11:35 UTC, danieldgt commented on src/util/Combinatorics.java
> +    public static List<Set> allCombinationsOf(Set objects) {
when you say, generic method, I may do that:

public static List<Set<Object>> allCombinationsOf(Set<? extends Object> objects) {
        List<Set<Object>> result = new ArrayList<Set<Object>>();
.....

2017-01-12 11:36 UTC, danieldgt commented on src/util/Combinatorics.java
> +    public static List<Set> allCombinationsOf(Set objects, int maxSize) {
ok, I forgot

2017-01-12 18:57 UTC, closed without merging