Range Enrich
LaNoC-UFC/rsbr pull request #36
Opened 2016-09-28 20:52 UTC by rafaelgmota

Implementation of range contains, equals, includes, overlaps and abuts. 
The implementation of combination and isContiguous are missing and will be done.

2016-09-28 21:27 UTC, jmferreiratech requested changes
Small changes. Only the unit tests will require more of your work.

2016-09-28 21:27 UTC, jmferreiratech commented on src/util/Range.java
> +        if(x < min[0] || x > max[0])
These three-line portion could be simplified to an one-line return.

2016-09-28 21:27 UTC, jmarcelof commented on src/util/Range.java
> +        if (numberOfDimensions < 2 || numberOfDimensions > 2)
It could check like this: "numberOfDimensions != 2"

2016-09-28 21:27 UTC, jmarcelof commented on src/util/Range.java
> +            if(x < min[0] || x > max[0] || y < min[1] || y > max[1])
These three-line portion could be simplified to an one-line return

2016-09-28 21:27 UTC, jmarcelof commented on tests/RangeTest.java
> +        Assert.assertTrue(range1.equals(range2));
You could use Assert.assertEquals here. It'll call your overrided equals method.

2016-09-28 21:27 UTC, jmarcelof commented on tests/RangeTest.java
> +public class RangeTest {
Each comment you put inside a unit test seems to indicate the start of a new unit test and so you should break them to smaller unit tests with one meaning each.

2016-09-28 21:27 UTC, jmarcelof commented on tests/RangeTest.java
> +    @Test
You could show first all unit tests for OneDimensionalRanges then those to TwoDimensionalRanges

2016-09-28 21:27 UTC, jmarcelof commented on src/util/Range.java
> +    public boolean includes(Range arg) {
We like to call same class objects passed as parameter, "that" to contrast with "this" and in this case is more uniform to use the "this" specifier and make the same kind of attribute access (directly or by accessors).

2016-09-28 21:27 UTC, jmarcelof commented on src/util/Range.java
> +        else {
We don't need else here.

2016-09-28 21:27 UTC, jmarcelof commented on src/util/Range.java
> +        for(int i = 0; i < numberOfDimensions; i++) {
Take care with the number of dimensions of parameters.

2016-09-28 21:27 UTC, jmarcelof commented on src/util/Range.java
> +        for(int i = 0 ; i < numberOfDimensions; i++)
Make more uniform use of curly braces for one statement blocks. There's no explicit convention but we'd prefer always put curly braces.

2016-09-28 21:27 UTC, jmarcelof commented on src/util/Range.java
> +
Delete that line.

2016-09-28 22:58 UTC, jmarcelof commented
Please put the issue number on the commit message.

2016-09-29 13:15 UTC, rafaelgmota commented on src/util/Range.java
> +        if(x < min[0] || x > max[0])
Done

2016-09-29 13:15 UTC, rafaelgmota commented on src/util/Range.java
> +        if (numberOfDimensions < 2 || numberOfDimensions > 2)
Done

2016-09-29 13:15 UTC, rafaelgmota commented on src/util/Range.java
> +            if(x < min[0] || x > max[0] || y < min[1] || y > max[1])
Done

2016-09-29 13:15 UTC, rafaelgmota commented on src/util/Range.java
> +        else {
Done

2016-09-29 13:15 UTC, rafaelgmota commented on src/util/Range.java
> +    public boolean includes(Range arg) {
Done

2016-09-29 13:15 UTC, rafaelgmota commented on src/util/Range.java
> +        for(int i = 0 ; i < numberOfDimensions; i++)
Done

2016-09-29 13:15 UTC, rafaelgmota commented on src/util/Range.java
> +
Done

2016-09-29 13:17 UTC, rafaelgmota commented on src/util/Range.java
> +        for(int i = 0; i < numberOfDimensions; i++) {
Done

2016-09-29 13:56 UTC, rafaelgmota commented
RangeTest was split into two files, one for one dimension range and another to two dimension ones.
The above improvements were done in both files.

2016-09-29 14:47 UTC, jmferreiratech requested changes
More improvements. Thanks

2016-09-29 14:47 UTC, jmarcelof commented on src/util/Range.java
> +        return true;
I think that is more clear if you use "return (min[0] <= x && x <= max[0]);"

2016-09-29 14:47 UTC, jmarcelof commented on src/util/Range.java
> +        return true;
Same idea as before.

2016-09-29 14:47 UTC, jmarcelof commented on src/util/Range.java
> +        Range other = (Range)arg;
Name it "that" and use "this" to contrast.

2016-09-29 14:47 UTC, jmarcelof commented on src/util/Range.java
> +        for(int i = 0 ; i < numberOfDimensions; i++) {
remove the space after "int i = 0"

2016-09-30 17:25 UTC, rafaelgmota commented
Implementation of isContiguous, only valid for one and two dimensions, need to be extended for three dimensions.

2016-09-30 18:44 UTC, rafaelgmota commented
Implementation of combination Range method

2016-10-03 13:25 UTC, rafaelgmota commented
Using Range functions at Region.java and RBR.java

2016-10-03 13:28 UTC, rafaelgmota commented
Refactoring of Range.combination(). 
Using Math.min() and Math.max()

2016-10-03 13:58 UTC, jmferreiratech requested changes
Fix these points and I'll merge it. Thanks

2016-10-03 13:58 UTC, jmarcelof commented on src/util/Range.java
> +    private Range(int[]min, int[]max) {
You don't need it.

2016-10-03 13:58 UTC, jmarcelof commented on src/util/Range.java
> +        return (x >= min[0]&&x <= max[0]&&y >= min[1]&&y <= max[1]);
Put spaces around operators.

2016-10-03 13:58 UTC, jmarcelof commented on src/util/Range.java
> +           }
Align this close brace.

2016-10-03 13:58 UTC, jmarcelof commented on src/util/Range.java
> +            if(that.min(i) < this.min(i) || that.max(i) > this.max(i)) {
Couldn't you use the contains() method here?

2016-10-03 13:58 UTC, jmarcelof commented on src/util/Range.java
> +            if(that.max(i) < this.min(i) || that.min(i) > this.max(i)) {
Couldn't you use the contains() method here also?

2016-10-04 18:14 UTC, rafaelgmota commented on src/util/Range.java
> +            if(that.min(i) < this.min(i) || that.max(i) > this.max(i)) {
The above logic is valid for one and two dimensions Range and we have one contains() for each dimension. So, will be necessary some if/else to treat each dimension diferently.

2016-10-04 18:15 UTC, rafaelgmota commented on src/util/Range.java
> +            if(that.max(i) < this.min(i) || that.min(i) > this.max(i)) {
Same as above

2016-10-04 18:17 UTC, rafaelgmota commented
fix lasts comments

2016-10-04 18:40 UTC, jmferreiratech approved these changes

2016-10-04 18:43 UTC, merged