Policy separation
LaNoC-UFC/rsbr pull request #37
Opened 2016-10-04 14:31 UTC by leonelmaia

Separated policy  from SR using a interface to connect SR to the policy.

2016-10-04 14:57 UTC, rmilfont requested changes
Little changes in order to make the code clearer.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/SR.java
> +	BidimensionalPolicy politica = new BidimensionalPolicy();
Change this variable name. Never use PT-BR!

2016-10-04 14:57 UTC, rmilfont commented on src/rsbr.java
> +import sbr.BidimensionalPolicy;
Squash the "import" using *.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +public class BidimensionalPolicy implements SBRPolicy {
Change this name to "BidimensionalSBRPolicy".

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +	/*
Remove the comments.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +
Remove this blank line.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +
Remove this blank line.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +
Remove this blank line.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +
Remove this blank line.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +			if (got != null)
Put the curly brackets for "if" statement

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +				if (RRIndex[1] == ((RRIndex[0] + 1) % 4))
Put the curly brackets for "if" statement

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +				else
Put the curly brackets for "else" statement

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +
Remove these blank lines.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/SBRPolicy.java
> +
Remove this blank line.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/SBRPolicy.java
> +
Remove this blank line.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +
Remove this blank line.

2016-10-04 14:57 UTC, rmilfont commented on src/sbr/BidimensionalPolicy.java
> +import util.Edge;
Squash the "import" using *.

2016-10-04 14:59 UTC, rmilfont commented
The conflict occurred because you didn´t follow the steps before push your code. Pay attention at https://github.com/LaNoC-UFC/GitHub-roadmap#7-after-pull-request-actions , case 1.

2016-10-04 17:31 UTC, rmilfont commented
You didn´t set the commit template, please see: https://github.com/LaNoC-UFC/GitHub-roadmap#3-configure-the-commit-template , item 3.

2016-10-04 20:50 UTC, jmarcelof commented
Next time be sure to create a new branch instead of modifying the develop.

2016-10-07 18:49 UTC, jmferreiratech requested changes
Please try to always use curly braces, even with one-statement block.

2016-10-07 18:49 UTC, jmarcelof commented on .gitignore
> -*~
You shouldn't remove 'out/', '.idea' and '*~'.

2016-10-07 18:49 UTC, jmarcelof commented on src/sbr/SBRPolicy.java
> +
You can keep all imports together.

2016-10-07 18:49 UTC, jmarcelof commented on src/rsbr.java
> +
Remove this extra line.

2016-10-11 12:45 UTC, jmferreiratech approved these changes

2016-10-11 12:46 UTC, merged