Transforming ip and op strings into Sets and change restrictions type
LaNoC-UFC/rsbr pull request #40
Opened 2016-10-05 19:47 UTC by rafaelgmota

With input and output ports type modification, we get ride of a lot of string manipulation and make the code more readable.

With restrictions type modification, we simplify addRestriction and getRestriction methods

2016-10-05 20:16 UTC, rmilfont requested changes

2016-10-05 20:16 UTC, rmilfont commented on src/rbr/Region.java
>  	// @ToDo inputPortsSet and outputPortsSet could actually be Sets. This would ease many operations on them:
Remove these comment lines.

2016-10-05 20:16 UTC, rmilfont commented on src/util/GraphRestrictions.java
> +    //
Remove this line.

2016-10-05 20:16 UTC, rmilfont commented on src/rbr/RBR.java
>  		for (rbr.Region reg : regionsForVertex.get(src))
Put the braces for 'for' statement.

2016-10-05 20:16 UTC, rmilfont commented on src/rbr/Region.java
> +		Set<Character> ipr1 = r1.inputPorts();
Rename 'ipr' variables for a more comprehensive name

2016-10-05 20:16 UTC, rmilfont commented on src/rbr/Region.java
> +		Set<Character> r1Op = r1.outputPorts();
Rename 'rNOp' variables for a more comprehensive name

2016-10-05 20:16 UTC, rmilfont commented on src/rbr/RoutingTableGenerator.java
>  import java.io.IOException;
Squash the imports using '*'.

2016-10-06 12:29 UTC, rafaelgmota commented
Done above modifications and get ride of getIpMerged and getOpMerged

2016-10-06 13:21 UTC, jmferreiratech requested changes
Good job! Make these few mods and I'll upstream it.

2016-10-06 13:21 UTC, jmferreiratech commented on src/rbr/RBR.java
> +					if (!op.containsAll(b.getOp()))
You don't need to check it, do you?

2016-10-06 13:21 UTC, jmferreiratech commented on src/paths_gen/PathFinder.java
> +        char inputPort = currentSrc.edge(predecessor).color();
Use a Character.

2016-10-06 13:21 UTC, jmferreiratech commented on src/rbr/RBR.java
> +					if (!ip.containsAll(b.getIp())) {
You don't need to check it, do you?

2016-10-06 13:21 UTC, jmferreiratech commented on src/rbr/RBR.java
> +			Set<Vertex> dst = new HashSet<>();
This line indentation looks weird on github.

2016-10-06 13:21 UTC, jmferreiratech commented on src/rbr/RBR.java
> +				return (Character)reg.outputPorts().toArray()[0];
You really need this cast?

2016-10-06 13:21 UTC, jmferreiratech commented on src/rbr/Region.java
>  		this.outputPortsSet = op;
Maybe is more safe to make a copy here as these sets could be changed by the caller.

2016-10-06 13:21 UTC, jmferreiratech commented on src/rbr/Region.java
> +	private Set<Character> outputPortsSet;
Rename those variables: remove the Set terminator.

2016-10-06 13:21 UTC, jmarcelof commented on src/rbr/Region.java
> +				|| that.outputPorts().containsAll(this.outputPorts())));
I'd rather keep the opIsSubset method with these two conditions. Maybe changing its name.

2016-10-06 13:21 UTC, jmarcelof commented on src/sbr/SR.java
> +						restrictions.addRestriction(Starting, link.color(), oPStarting);
addRestriction always receive only one restriction, so you don't need to receive a Set for 'ip' and 'op' (if you needed, you should call it addRestrictions). Making it receive a Character will simplify the setrestrictions method.

2016-10-06 18:33 UTC, rafaelgmota commented
Above modifications were done

2016-10-06 19:06 UTC, jmferreiratech approved these changes

2016-10-06 19:07 UTC, merged