Avoid duplicated items
LaNoC-UFC/rsbr pull request #46
Opened 2016-10-08 20:22 UTC by erodac

Use of Set collection on the vertex routing paths instead of ArrayList to avoid any duplicated items on the collection. To modify this and ensure the exclusivity of each item, was necessary to override the equals() and hashCode() methods of RoutingOption class. An unitary test was successfully done.

2016-10-08 21:06 UTC, jmferreiratech requested changes

2016-10-08 21:06 UTC, jmarcelof commented on src/rbr/RBR.java
>  	private void addRoutingPath(Vertex v, Set<Character> ip, Vertex dst, Set<Character> op) {
Could you please add a Ref commit to get ride of this method and replace the calls made to it by "routingPathForVertex.get(v).add(new RoutingOption(ip, dst, op));"?

2016-10-08 21:06 UTC, jmarcelof commented on src/rbr/RoutingOption.java
> +
Remove that blank line.

2016-10-08 21:06 UTC, jmarcelof commented on tests/rbr/RoutingPathsDuplicationTest.java
> +import java.util.HashSet;
Squash these imports with *

2016-10-08 21:06 UTC, jmarcelof commented on tests/rbr/RoutingPathsDuplicationTest.java
> +		RoutingOption option1, option2;
Merge declaration and initialization.

2016-10-08 21:06 UTC, jmarcelof commented on tests/rbr/RoutingPathsDuplicationTest.java
> +		Set<Character> ip = new HashSet<>();
Declare variables more closer to their use.

2016-10-08 21:06 UTC, jmarcelof commented on tests/rbr/RoutingPathsDuplicationTest.java
> +		Assert.assertEquals(option1.hashCode(), option2.hashCode());
This is another test.

2016-10-08 21:06 UTC, jmarcelof commented on tests/rbr/RoutingPathsDuplicationTest.java
> +		Assert.assertEquals("option2: " + option2.hashCode() + " option1: " + option1.hashCode(), option2, option1);
The message has no relation with the assert itself.

2016-10-08 21:06 UTC, jmarcelof commented on tests/rbr/RoutingPathsDuplicationTest.java
> +
Remove this blank line.

2016-10-08 21:06 UTC, jmarcelof commented on tests/rbr/RoutingPathsDuplicationTest.java
> +public class RoutingPathsDuplicationTest {
Name it only RoutingPathTest

2016-10-13 14:49 UTC, erodac commented
All changes were done.

2016-10-13 14:58 UTC, jmferreiratech approved these changes

2016-10-13 14:58 UTC, merged