Extract adjuncts from Vertex class
LaNoC-UFC/rsbr pull request #58
Opened 2016-10-11 21:09 UTC by rmilfont

Now Vertex class are more simple. The adjunct's list and other useful
methods (involving adjuncts) can be find from Graph class.
Commit:Mod
TaskNumber:#57

2016-10-11 23:36 UTC, jmferreiratech requested changes

2016-10-11 23:36 UTC, jmarcelof commented on src/util/LinkWeightTracker.java
> +    private Collection<Edge> getEdgesOf(Path p){
Rename it to edgesOf

2016-10-11 23:36 UTC, jmarcelof commented on src/rbr/RBR.java
> +		Edge newSrc = graph.getAdjunct(src, opColor);
"newSrc" sounds weird to me.

2016-10-11 23:36 UTC, jmarcelof commented on src/util/Graph.java
> +    public ArrayList<Edge> getAdjuncts(Vertex v) {
rename it to adjunctsOf(Vertex src) or only adjuncts(Vertex src)

2016-10-11 23:36 UTC, jmarcelof commented on src/util/Graph.java
> +    public Edge getAdjunct(Vertex src, Vertex dst){
Rename it to adjunct(Vertex from, Vertex to)

2016-10-11 23:36 UTC, jmarcelof commented on src/util/Graph.java
> +    public Edge getAdjunct(Vertex v, Character color){
Rename it to adjunctOf()

2016-10-11 23:36 UTC, jmarcelof commented on src/util/Graph.java
> +    private Map<Vertex, ArrayList<Edge>> adjuncts;
Use a more abstract type instead of ArrayList

2016-10-11 23:36 UTC, jmarcelof commented on src/util/Graph.java
> +		Edge e = new Edge(src, dst, cor);
Here you should call only addEdge(new Edge(src, dst, cor));

2016-10-11 23:36 UTC, jmarcelof commented on src/util/Graph.java
> +    void findAdjuncts(){
I cannot see why you need this method since addEdge() do this job already.

2016-10-12 00:00 UTC, rmilfont commented on src/util/LinkWeightTracker.java
> +    private Collection<Edge> getEdgesOf(Path p){
Done.

2016-10-12 00:01 UTC, rmilfont commented on src/util/Graph.java
> +    private Map<Vertex, ArrayList<Edge>> adjuncts;
Done.

2016-10-12 00:04 UTC, rmilfont commented on src/util/Graph.java
> +    public Edge getAdjunct(Vertex v, Character color){
Done.

2016-10-12 00:04 UTC, rmilfont commented on src/util/Graph.java
> +    public Edge getAdjunct(Vertex src, Vertex dst){
Done.

2016-10-12 00:10 UTC, rmilfont commented on src/util/Graph.java
> +    void findAdjuncts(){
With the above suggestion, I will remove the method.

2016-10-12 00:10 UTC, rmilfont commented on src/util/Graph.java
> +		Edge e = new Edge(src, dst, cor);
Done.

2016-10-12 00:10 UTC, rmilfont commented on src/util/Graph.java
> +    public ArrayList<Edge> getAdjuncts(Vertex v) {
Done.

2016-10-12 00:12 UTC, rmilfont commented on src/rbr/RBR.java
> +		Edge newSrc = graph.getAdjunct(src, opColor);
Done.

2016-10-12 00:17 UTC, rmilfont commented
All done.

2016-10-12 12:04 UTC, jmferreiratech approved these changes

2016-10-12 12:30 UTC, merged