Create a new constructor for RoutingOption
LaNoC-UFC/rsbr pull request #67
Opened 2016-10-21 16:27 UTC by matheus220

The new constructor receives a single input and output port (Character) instead of a Set.

Commit: Add

TaskNumber: #42

2016-10-21 17:50 UTC, jmferreiratech requested changes
Use your new constructor at https://github.com/LaNoC-UFC/rsbr/blob/develop/src/rbr/RBR.java#L79

2016-10-21 17:50 UTC, jmferreiratech commented on src/rbr/RoutingOption.java
> +        this.ip.add(ip);
Before using ip/op you need to instantiate them.

2016-10-23 01:34 UTC, jmferreiratech requested changes

2016-10-23 01:34 UTC, jmferreiratech commented on src/rbr/RBR.java
> +                        op = graph.adjunct(sw, path.get(path.indexOf(sw) + 1)).color();
Put 'op' declaration together with the assignment.

2016-10-23 01:34 UTC, jmferreiratech commented on src/rbr/RoutingOption.java
> +
Remove the trailing spaces.

2016-10-23 01:34 UTC, jmferreiratech commented on src/rbr/RoutingOption.java
> +
Remove the trailing spaces.

2016-10-24 13:07 UTC, jmferreiratech approved these changes

2016-10-24 13:38 UTC, rmilfont approved these changes

2016-10-24 13:50 UTC, merged