Rename variables names from dimX to columns and dimY to rows
LaNoC-UFC/rsbr pull request #83
Opened 2016-10-27 20:03 UTC by rafaelgmota

This patch makes uniform the use of dimensions and coordinates to specify network topology avoiding confusion.

#81 was caused by a misunderstood related with the issue above.

:) (y)

2016-10-27 21:05 UTC, jmferreiratech requested changes
There'are more uses of 'dimX' and 'dimY' through the code, please get ride of them all once for all.

2016-10-27 21:05 UTC, jmarcelof commented on src/rsbr.java
> +        //int dim = 4;
It wasn't necessary to change these variables values.

2016-10-27 21:06 UTC, jmarcelof commented
Take the chance to fix the typo at the commit message.

2016-10-28 12:51 UTC, rafaelgmota commented
Modifications done, please verify if there is more errors to correct

2016-10-28 13:22 UTC, jmferreiratech approved these changes

2016-10-28 13:40 UTC, rmilfont approved these changes

2016-10-28 13:40 UTC, merged