All paths between two vertex
LaNoC-UFC/rsbr pull request #92
Opened 2016-11-10 21:05 UTC by danieldgt

Include methods in the PathFinder class to define all paths between two vertex

Commit:add

2016-11-11 01:45 UTC, jmferreiratech requested changes

2016-11-11 01:45 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +        Set<String> alreadyFoundPairs = new HashSet<>();
Do you need 'alreadyFoundPairs'?

2016-11-11 01:45 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +        int nPairs = graph.getVertices().size() * (graph.getVertices().size() - 1);
Do you really need 'nPairs'?

2016-11-11 01:45 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +            for(Path path : valid){
Put a space before open brackets.

2016-11-11 01:45 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +    private ArrayList<Path> computeOneHopPaths(Vertex src) {
Rename it to 'oneHopPathsFrom' and return a 'List' instead of 'ArrayList'.

2016-11-11 01:45 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +    private ArrayList<Path> computeOneHopPaths(Vertex src) {
Don't you think that 'computeOneHopPaths' could use this method?

2016-11-11 01:45 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +    private ArrayList<Path> advanceOneHopNoMinimal(Path p, Set<String> alreadyFoundPairs) {
Rename it to something as 'oneHopMorePathsFrom' and return a 'List' instead of 'ArrayList'.

2016-11-11 01:45 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +    public List<Path> allPathsComputationByVertex(Vertex src, Vertex dst) {
Rename it to something as 'allPathsBetween'.

2016-11-11 01:45 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +    private ArrayList<Path> advanceOneHopNoMinimal(ArrayList<Path> previouslyFoundPaths, Set<String> alreadyFoundPairs) {
Rename it to 'oneHopMorePaths' and return a 'List' instead of 'ArrayList'.

2016-11-21 21:25 UTC, rmilfont approved these changes

2016-11-22 14:06 UTC, rafaelgmota approved these changes

2016-11-22 17:14 UTC, jmferreiratech requested changes

2016-11-22 17:14 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +    public List<Path> allPathsBetweenVertexs(Vertex src, Vertex dst) {
allPathsBetweenVertices

2016-11-22 17:14 UTC, jmarcelof commented on src/paths_gen/PathFinder.java
> +        // N = 1 hop
Remove that commented line or put a commentary to "N > 1 hop"

2016-11-30 21:02 UTC, jmferreiratech approved these changes

2016-11-30 21:59 UTC, rmilfont approved these changes

2016-11-30 22:12 UTC, merged