Unit test make regions
LaNoC-UFC/rsbr pull request #96
Opened 2016-11-23 03:46 UTC by matheus220

Turn RBR.makeRegions() package private and add unit tests to it.

Commit:Add

TaskNumber:#72

2016-11-23 12:58 UTC, jmferreiratech requested changes

2016-11-23 12:58 UTC, jmarcelof commented on src/rbr/RBR.java
>      // Make regions only with correct destinations
Please, remove this commented line.

2016-11-23 12:58 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +    Set<Character> ip = new HashSet<>();
Couldn't these be private?

2016-11-23 12:58 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +        for(Region adjustedRegion : rbr.makeRegions(dst, ip, op)) {
'adjustedRegion' doesn't seem a good name, does it?

2016-11-23 12:58 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +    public void createdRegionsHaveNoOutsider() throws Exception {
Rename the tests that make assertions for each region to make it clear. This one I'd name 'createdRegionHasNoOutsider'.

2016-11-23 12:58 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +        ip.add('I');
Rename the variables to something less coded and that reflect multiplicity: 'ip' to 'inputPorts', 'op' to 'outputPorts', 'dst' to 'destinations' and so forth.

2016-11-23 12:58 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +        List<Region> teste = rbr.makeRegions(dst, ip, op);
Do you need this 'teste' variable?

2016-11-23 13:05 UTC, rafaelgmota requested changes

2016-11-23 13:05 UTC, rafaelgmota commented on tests/rbr/AdjustRegionsTest.java
> +    @Test
This modificaition is already done at pull request #95

2016-11-23 13:05 UTC, rafaelgmota commented on tests/rbr/MakeRegionsTest.java
> +}
You can improve this by putting some test to verify if the number of created regions is correct and if the max and min of regions box is also correct.

2016-11-23 14:03 UTC, jmarcelof commented on tests/rbr/AdjustRegionsTest.java
> +    @Test
Rebase your patch on top of upstream.

2016-11-23 20:14 UTC, matheus220 commented on tests/rbr/MakeRegionsTest.java
> +}
Is it not sufficient to verify that the set of destinations is the same as the original and that no region has outsiders?

2016-11-25 15:41 UTC, jmferreiratech commented on tests/rbr/MakeRegionsTest.java
> +}
I think it's good to assert the number of generated regions.

2016-11-25 15:45 UTC, jmferreiratech requested changes
I think you can add two more useful tests: one that shows that each generated region box do not include the others generated regions' boxes. And another that shows that each generated region box isn't contiguous with any other generated region box.
These tests show that the method tries to minimize the number of generated regions.

2016-11-25 21:08 UTC, matheus220 commented
Ok, good idea. I'm working on it and I had a question. For a network with dimensions 4 x 4, with destinations placed alternately, similar to a chess. The minimum number of regions is 8?

2016-11-26 03:04 UTC, jmarcelof commented
Yes, if you have a 'chess pattern', the minimal number of regions is the number of destinations (as you do not have any vertex side-by-side).

2016-12-01 00:01 UTC, jmferreiratech requested changes

2016-12-01 00:01 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +    public void createdRegionsHaveSameInputPortsOriginals() throws Exception {
Make the tests' name more 'sentence like'. Something as "createdRegionsHaveOriginalInputPorts".

2016-12-01 00:01 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +    public void createdRegionsHaveSameOutputPortsOriginals() throws Exception {
Idem

2016-12-01 00:01 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +        Set<Vertex> originalsDst = new HashSet<>(destinations);
Do you really need to copy the destinations set?

2016-12-01 00:01 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +    public void createdRegionsHaveSameDestinationsOriginals() throws Exception {
I'd name it "createdRegionsCoverAllOriginalDestinations".

2016-12-01 00:01 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +        Assert.assertEquals(createdRegions.size(), 5);
It does not make sense to assert that here. You can remove it by now. And then you'll not need the 'createdRegions' variable.

2016-12-01 00:01 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +    public void createdRegionsAreDisjoint() throws Exception {
They do not need to be disjoint. Then, you can drop it.

2016-12-01 00:01 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +    public void createdMinimalNumberRegions() throws Exception {
Make the test name more 'sentence like'.

2016-12-01 23:49 UTC, jmferreiratech requested changes
Make this changes and I'll merge it. Thanks.

2016-12-01 23:49 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +        Set<Vertex> originalsDst = new HashSet<>(destinations);
You don't need 'originalsDst', do you? I think you can use 'destinations' directly.

2016-12-01 23:49 UTC, jmarcelof commented on tests/rbr/MakeRegionsTest.java
> +        Set<Vertex> destinationsCreatedRegions = new HashSet<>();
Instantiate the variable right before you use it.

2016-12-02 20:05 UTC, matheus220 commented
And this way?

2016-12-02 20:32 UTC, jmferreiratech approved these changes

2016-12-05 11:23 UTC, merged